"""taiko-trainer uploader companion.

Small standalone agent that watches an osu! `Data/r/` folder and POSTs new
`.osr` replays to a hosted taiko-trainer instance. Restores the seamless
"play → your report updates" loop that the local single-user app has for
users of the hosted service.

Command surface:

    taiko-uploader init        interactive setup (server url, token,
                               folder path) → writes ~/.taiko-trainer/uploader.toml
    taiko-uploader run         start the watcher (foreground; ^C to stop)
    taiko-uploader status      show config + last N uploads
    taiko-uploader backfill    scan the folder, upload anything not yet
                               known (no daemon)

Config file: ~/.taiko-trainer/uploader.toml
    server_url      = "https://your-service.com"
    api_token       = "tt_uploader_..."
    replays_folder  = "C:/Users/YOU/AppData/Local/osu!/Data/r"
    poll_interval_s = 60      # optional: fallback poll cadence if
                              # watchdog misses events

State file: ~/.taiko-trainer/uploader.state.db
    Tracks (filename → uploaded_at, replay_id) so a restart or a rescan
    doesn't re-upload everything. Filename alone is a decent dedup key
    because osu! embeds the timestamp; content hash of the first 512 bytes
    disambiguates collisions.

Failure modes:
    401 Unauthorized  → token revoked. Log clearly, exit non-zero. User
                        must mint a new token via /settings/tokens and
                        `taiko-uploader init` again.
    403 Forbidden     → .osr player mismatch. Skip that file (someone
                        else's replay); DO NOT retry.
    409/dup           → server thinks it's already stored. Mark uploaded
                        locally, move on.
    5xx / network err → retry with backoff, keep going. In-memory queue
                        drains on next successful call.
"""
from __future__ import annotations

import hashlib
import os
import queue
import sqlite3
import sys
import time
import tomllib
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Optional

import httpx


# --- Paths ------------------------------------------------------------------

def _config_dir() -> Path:
    """Cross-platform user-config dir. On Windows expands to %USERPROFILE%,
    on Unix to $HOME. Both are stable across sessions."""
    return Path.home() / ".taiko-trainer"


def _config_path() -> Path:
    return _config_dir() / "uploader.toml"


def _state_path() -> Path:
    return _config_dir() / "uploader.state.db"


# --- Config -----------------------------------------------------------------

@dataclass(frozen=True)
class Config:
    server_url: str            # e.g. "https://taiko.example.com"
    api_token: str             # tt_uploader_...
    replays_folder: str        # absolute path
    poll_interval_s: int = 60


def load_config() -> Config:
    """Read the TOML config; raise FileNotFoundError with a helpful message
    if it doesn't exist."""
    p = _config_path()
    if not p.exists():
        raise FileNotFoundError(
            f"No uploader config at {p}\n"
            f"Run `taiko-uploader init` to create one."
        )
    with open(p, "rb") as fh:
        data = tomllib.load(fh)
    required = ("server_url", "api_token", "replays_folder")
    missing = [k for k in required if not data.get(k)]
    if missing:
        raise ValueError(
            f"Config {p} missing required fields: {', '.join(missing)}"
        )
    return Config(
        server_url=data["server_url"].rstrip("/"),
        api_token=data["api_token"],
        replays_folder=data["replays_folder"],
        poll_interval_s=int(data.get("poll_interval_s", 60)),
    )


def write_config(cfg: Config) -> None:
    """Serialize to TOML. Minimal quoting — TOML strings only need escaping
    for backslashes and quotes, and Windows paths have backslashes, so we
    use forward-slash-normalized paths in the config."""
    _config_dir().mkdir(parents=True, exist_ok=True)
    p = _config_path()
    body = (
        f'# taiko-trainer uploader companion config\n'
        f'# Generated by `taiko-uploader init`. Edit as needed.\n'
        f'\n'
        f'server_url      = "{cfg.server_url}"\n'
        f'api_token       = "{cfg.api_token}"\n'
        f'replays_folder  = "{Path(cfg.replays_folder).as_posix()}"\n'
        f'poll_interval_s = {cfg.poll_interval_s}\n'
    )
    p.write_text(body, encoding="utf-8")
    # Restrict permissions on Unix — the file contains a bearer token.
    # Windows doesn't have chmod in the same shape; the token isn't a
    # world-secret on your own PC anyway.
    try:
        os.chmod(p, 0o600)
    except OSError:
        pass


# --- State ------------------------------------------------------------------

class State:
    """SQLite-backed tracker of which files have been uploaded, so restarts
    and backfills don't re-upload."""

    _SCHEMA = """
    CREATE TABLE IF NOT EXISTS uploaded (
        filename       TEXT PRIMARY KEY,
        content_hash   TEXT NOT NULL,      -- sha256 of first 512 bytes
        replay_id      INTEGER,             -- id returned by the server
        uploaded_at    TEXT NOT NULL,
        map_title      TEXT,
        map_version    TEXT,
        mods           TEXT,
        accuracy       REAL
    );
    """

    def __init__(self, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        self.conn = sqlite3.connect(str(path))
        self.conn.row_factory = sqlite3.Row
        self.conn.executescript(self._SCHEMA)
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()

    def known(self, filename: str) -> bool:
        row = self.conn.execute(
            "SELECT 1 FROM uploaded WHERE filename = ?", (filename,)
        ).fetchone()
        return row is not None

    def record(
        self,
        filename: str,
        content_hash: str,
        replay_id: Optional[int],
        summary: dict | None = None,
    ) -> None:
        s = summary or {}
        self.conn.execute(
            """
            INSERT OR REPLACE INTO uploaded
                (filename, content_hash, replay_id, uploaded_at,
                 map_title, map_version, mods, accuracy)
            VALUES (?, ?, ?, datetime('now'), ?, ?, ?, ?)
            """,
            (
                filename, content_hash, replay_id,
                s.get("map_title"), s.get("map_version"),
                s.get("mods"), s.get("accuracy"),
            ),
        )
        self.conn.commit()

    def recent(self, limit: int = 10) -> list[dict]:
        rows = self.conn.execute(
            "SELECT * FROM uploaded ORDER BY uploaded_at DESC LIMIT ?", (limit,)
        ).fetchall()
        return [dict(r) for r in rows]


def _hash_head(path: Path, n: int = 512) -> str:
    """sha256 of the first N bytes. Cheap fingerprint that disambiguates
    files with the same name (rare but possible after rescan-with-move)
    without reading the whole replay just to dedup."""
    with open(path, "rb") as fh:
        head = fh.read(n)
    return hashlib.sha256(head).hexdigest()


# --- osu! folder auto-detection --------------------------------------------

def detect_replays_folder() -> Optional[Path]:
    """Best-effort probe for the osu! Data/r folder. Returns None if
    nothing plausible is found; caller falls back to manual entry."""
    candidates: list[Path] = []
    # Windows standard install (osu! is per-user in %LOCALAPPDATA%)
    localappdata = os.environ.get("LOCALAPPDATA")
    if localappdata:
        candidates.append(Path(localappdata) / "osu!" / "Data" / "r")
    # Older / manual installs
    candidates.append(Path("C:/osu!/Data/r"))
    candidates.append(Path("C:/Program Files/osu!/Data/r"))
    candidates.append(Path("C:/Program Files (x86)/osu!/Data/r"))
    # Linux (osu-lazer / stable-under-wine)
    home = Path.home()
    candidates.append(home / ".local" / "share" / "osu-wine" / "osu!" / "Data" / "r")
    candidates.append(home / "osu!" / "Data" / "r")
    # macOS (rare for taiko but included)
    candidates.append(home / "Library" / "Application Support" / "osu!" / "Data" / "r")
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


# --- Upload -----------------------------------------------------------------

@dataclass(frozen=True)
class UploadOutcome:
    ok: bool                       # True on 201/200 OR intentional skip
    skip_reason: str | None = None # "duplicate", "foreign_replay", "unauth" ...
    replay_id: int | None = None
    summary: dict | None = None
    retryable: bool = False        # True → put back on the queue
    error: str | None = None


def upload_one(client: httpx.Client, cfg: Config, path: Path) -> UploadOutcome:
    """POST one .osr. Returns a structured outcome the caller uses to
    decide state updates + retries."""
    try:
        with open(path, "rb") as fh:
            files = {"file": (path.name, fh, "application/x-osu-replay")}
            resp = client.post(
                f"{cfg.server_url}/api/v1/replays",
                headers={"Authorization": f"Bearer {cfg.api_token}"},
                files=files,
                timeout=60.0,
            )
    except (httpx.ConnectError, httpx.ReadTimeout, httpx.RemoteProtocolError) as e:
        return UploadOutcome(ok=False, retryable=True, error=f"network: {e}")

    if resp.status_code in (200, 201):
        try:
            data = resp.json()
        except Exception:
            data = {}
        return UploadOutcome(
            ok=True,
            replay_id=data.get("replay_id"),
            summary=data if isinstance(data, dict) else None,
        )
    if resp.status_code == 401:
        return UploadOutcome(ok=False, skip_reason="unauth", retryable=False,
                             error=resp.text[:200])
    if resp.status_code == 403:
        return UploadOutcome(ok=False, skip_reason="foreign_replay", retryable=False,
                             error=resp.text[:200])
    if resp.status_code == 409:
        return UploadOutcome(ok=False, skip_reason="duplicate", retryable=False)
    if 500 <= resp.status_code < 600:
        return UploadOutcome(ok=False, retryable=True,
                             error=f"HTTP {resp.status_code}: {resp.text[:200]}")
    # 4xx other than auth/dup — treat as a real failure, don't retry
    return UploadOutcome(ok=False, retryable=False,
                         error=f"HTTP {resp.status_code}: {resp.text[:200]}")


# --- Loops ------------------------------------------------------------------

def backfill(cfg: Config, state: State, client: httpx.Client) -> tuple[int, int]:
    """Scan the folder once, upload anything not in state. Returns
    (uploaded, skipped) counts."""
    folder = Path(cfg.replays_folder)
    if not folder.is_dir():
        raise FileNotFoundError(f"replays folder not found: {folder}")
    uploaded = 0
    skipped = 0
    for p in sorted(folder.glob("*.osr")):
        if state.known(p.name):
            skipped += 1
            continue
        outcome = upload_one(client, cfg, p)
        if outcome.ok:
            h = _hash_head(p)
            state.record(p.name, h, outcome.replay_id, outcome.summary)
            print(f"  ✓ {p.name}  →  {outcome.summary.get('map_title', '?') if outcome.summary else 'ok'}")
            uploaded += 1
        elif outcome.skip_reason == "duplicate":
            state.record(p.name, _hash_head(p), None, None)
            skipped += 1
        elif outcome.skip_reason == "foreign_replay":
            print(f"  ⊘ {p.name}  →  not your replay, skipping")
            state.record(p.name, _hash_head(p), None, None)
            skipped += 1
        elif outcome.skip_reason == "unauth":
            print(f"\nERROR: token unauthorized ({outcome.error})", file=sys.stderr)
            print(f"Mint a new token at {cfg.server_url}/settings/tokens and run `taiko-uploader init`.", file=sys.stderr)
            sys.exit(2)
        else:
            print(f"  ✗ {p.name}  →  {outcome.error}", file=sys.stderr)
    return uploaded, skipped


def watch_and_upload(cfg: Config, state: State, client: httpx.Client) -> None:
    """Watchdog-driven main loop. New .osr files hit the handler which
    enqueues them; a worker drains the queue synchronously with retry
    backoff. A periodic poll thread guards against events the OS missed."""
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler

    q: "queue.Queue[Path]" = queue.Queue()

    class _Handler(FileSystemEventHandler):
        def _try_enqueue(self, path_str: str) -> None:
            p = Path(path_str)
            if p.suffix.lower() != ".osr":
                return
            # Wait a beat — osu! sometimes writes .osr in two flushes
            # and we want the second one landed before we read.
            time.sleep(0.5)
            q.put(p)

        def on_created(self, ev):
            if not ev.is_directory:
                self._try_enqueue(ev.src_path)

        def on_moved(self, ev):
            # osu! may write to a .tmp then rename to .osr — handle both.
            if not ev.is_directory:
                self._try_enqueue(ev.dest_path)

    obs = Observer()
    obs.schedule(_Handler(), cfg.replays_folder, recursive=False)
    obs.start()
    print(f"Watching {cfg.replays_folder} — press Ctrl+C to stop")

    # Fallback poller: every poll_interval_s, scan for new files.
    # Catches: OS events dropped, sleep/resume gaps, network shares
    # where inotify doesn't fire reliably.
    last_poll = time.time()

    try:
        while True:
            try:
                path = q.get(timeout=1.0)
            except queue.Empty:
                path = None

            if path is not None and not state.known(path.name):
                _process_one(client, cfg, state, path)

            if time.time() - last_poll > cfg.poll_interval_s:
                last_poll = time.time()
                folder = Path(cfg.replays_folder)
                if folder.is_dir():
                    for p in folder.glob("*.osr"):
                        if not state.known(p.name):
                            _process_one(client, cfg, state, p)
    except KeyboardInterrupt:
        print("\nStopping…")
    finally:
        obs.stop()
        obs.join()


def _process_one(client: httpx.Client, cfg: Config, state: State, path: Path) -> None:
    """Upload one file with retry backoff. Never raises; logs everything."""
    delay = 2.0
    while True:
        outcome = upload_one(client, cfg, path)
        if outcome.ok:
            state.record(path.name, _hash_head(path), outcome.replay_id, outcome.summary)
            summary = outcome.summary or {}
            title = summary.get("map_title", "?")
            mods = summary.get("mods", "")
            acc = summary.get("accuracy")
            acc_str = f"  {acc*100:.2f}%" if isinstance(acc, (int, float)) else ""
            mods_str = f" +{mods}" if mods and mods != "NM" else ""
            print(f"  ✓ {path.name}  →  {title}{mods_str}{acc_str}")
            return
        if outcome.skip_reason in ("duplicate", "foreign_replay"):
            state.record(path.name, _hash_head(path), None, None)
            reason = "duplicate" if outcome.skip_reason == "duplicate" else "not your replay"
            print(f"  ⊘ {path.name}  →  {reason}, skipping")
            return
        if outcome.skip_reason == "unauth":
            print(f"\nERROR: token unauthorized. Mint a new one and re-init.", file=sys.stderr)
            sys.exit(2)
        if not outcome.retryable:
            print(f"  ✗ {path.name}  →  {outcome.error}", file=sys.stderr)
            return
        # Retryable: back off, try again. Cap at 60s per retry.
        print(f"  … {path.name}  →  retry in {delay:.0f}s ({outcome.error})", file=sys.stderr)
        time.sleep(delay)
        delay = min(delay * 2, 60.0)


# --- CLI commands -----------------------------------------------------------

def _prompt(msg: str, default: str = "") -> str:
    """Prompt with an optional default shown in [brackets]. Empty response
    picks the default."""
    suffix = f" [{default}]" if default else ""
    val = input(f"{msg}{suffix}: ").strip()
    return val or default


def cmd_init() -> int:
    """Interactive setup. Autodetects the replays folder where possible,
    prompts for server URL + token, writes the config."""
    print("taiko-trainer uploader — first-time setup\n")

    server = _prompt("Server URL (e.g. https://your-service.com or http://localhost:8000)")
    if not server:
        print("Server URL is required.", file=sys.stderr)
        return 1
    token = _prompt("API token (from /settings/tokens on the server)")
    if not token.startswith("tt_uploader_"):
        print("That doesn't look like a taiko-trainer uploader token (should start with `tt_uploader_`).", file=sys.stderr)
        return 1

    detected = detect_replays_folder()
    default_folder = str(detected) if detected else ""
    folder = _prompt("Path to osu! replays folder (Data/r/)", default_folder)
    if not folder:
        print("Replays folder is required.", file=sys.stderr)
        return 1
    if not Path(folder).is_dir():
        print(f"WARNING: {folder} doesn't exist or isn't a directory. Continuing anyway; you can edit the config file later.", file=sys.stderr)

    cfg = Config(server_url=server.rstrip("/"), api_token=token, replays_folder=folder)
    write_config(cfg)
    print(f"\nWrote config to {_config_path()}")
    print(f"Run `taiko-uploader run` to start watching, or `taiko-uploader backfill` to upload existing replays.")
    return 0


def cmd_run() -> int:
    """Start the watcher loop.

    Does NOT auto-import your entire history on startup — that would be
    thousands of files for anyone with a real osu! folder and would take
    a long time before the watcher actually starts. If you want to import
    your history, use `taiko-uploader backfill` explicitly (once).

    On subsequent runs (state file exists with known uploads), does a
    quiet catch-up scan for files recorded while the uploader was off.
    """
    cfg = load_config()
    state = State(_state_path())

    # First run heuristic: state is empty → skip backfill, print a hint.
    # Second run onward: catch-up is fast (state already knows most files).
    with sqlite3.connect(str(_state_path())) as _c:
        known_count = _c.execute("SELECT COUNT(*) FROM uploaded").fetchone()[0]

    with httpx.Client() as client:
        if known_count == 0:
            folder_files = 0
            folder_p = Path(cfg.replays_folder)
            if folder_p.is_dir():
                folder_files = sum(1 for _ in folder_p.glob("*.osr"))
            if folder_files > 20:
                print(
                    f"First run: skipping catch-up ({folder_files} .osr files in "
                    f"{cfg.replays_folder}).\n"
                    f"To import your existing history, stop this and run "
                    f"`taiko-uploader backfill` first.\n"
                )
            else:
                print("First run: catching up on existing replays…")
                up, sk = backfill(cfg, state, client)
                print(f"Catch-up done: {up} uploaded, {sk} skipped\n")
        else:
            print("Catching up on any replays saved while offline…")
            up, sk = backfill(cfg, state, client)
            if up + sk > 0:
                print(f"Catch-up done: {up} uploaded, {sk} skipped\n")

        watch_and_upload(cfg, state, client)
    state.close()
    return 0


def cmd_backfill() -> int:
    """One-shot: scan and upload, no daemon. Useful for a first-time
    import or after a long offline period."""
    cfg = load_config()
    state = State(_state_path())
    with httpx.Client() as client:
        up, sk = backfill(cfg, state, client)
    state.close()
    print(f"\n{up} uploaded, {sk} skipped/known")
    return 0


def cmd_status() -> int:
    """Print config + recent uploads. Handy for debugging."""
    try:
        cfg = load_config()
    except FileNotFoundError as e:
        print(str(e), file=sys.stderr)
        return 1
    state = State(_state_path())
    print("Config:")
    print(f"  server:  {cfg.server_url}")
    print(f"  token:   {cfg.api_token[:24]}…")
    print(f"  folder:  {cfg.replays_folder}")
    recent = state.recent(limit=10)
    print(f"\nLast {len(recent)} uploads:")
    if not recent:
        print("  (none yet)")
    else:
        for r in recent:
            title = (r["map_title"] or "?")[:36]
            mods = r["mods"] or ""
            mods_str = f" +{mods}" if mods and mods != "NM" else ""
            acc = r["accuracy"]
            acc_str = f"  {acc*100:.2f}%" if isinstance(acc, (int, float)) else ""
            print(f"  {r['uploaded_at'][:16]}  {title}{mods_str}{acc_str}  ({r['filename']})")
    state.close()
    return 0


def main() -> int:
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help", "help"):
        print(__doc__, file=sys.stderr)
        return 0
    cmd = args[0]
    if cmd == "init":     return cmd_init()
    if cmd == "run":      return cmd_run()
    if cmd == "backfill": return cmd_backfill()
    if cmd == "status":   return cmd_status()
    print(f"unknown command: {cmd!r}. See `taiko-uploader --help`.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
