//! TOML config for the uploader — mirrors `src/taiko_trainer/uploader.py`'s
//! shape so a user who ran the tkinter binary before can reuse their existing
//! `~/.taiko-trainer/uploader.toml` unchanged.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// The production server, baked into the shipped binary. Users who paste a
/// token from taiko.umaladder.moe never need to touch this. Developers can
/// override in the TOML file for localhost testing.
pub const DEFAULT_SERVER_URL: &str = "https://taiko.umaladder.moe";

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Config {
    pub api_token: String,
    pub replays_folder: String,
    #[serde(default = "default_server_url")]
    pub server_url: String,
    #[serde(default = "default_poll_interval")]
    pub poll_interval_s: u64,
}

fn default_server_url() -> String { DEFAULT_SERVER_URL.to_string() }
fn default_poll_interval() -> u64 { 60 }

/// Same layout as the Python uploader — `~/.taiko-trainer/`.
///
/// Rationale: keeping the same location means users who already have the
/// tkinter binary set up don't need to re-enter their token when they
/// switch to the Tauri build. It's also where the state DB lives.
pub fn config_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".taiko-trainer")
}

pub fn config_path() -> PathBuf { config_dir().join("uploader.toml") }

pub fn state_path() -> PathBuf { config_dir().join("uploader.state.db") }

pub fn log_path() -> PathBuf { config_dir().join("uploader.log") }

/// Load the TOML file if it exists. Returns Ok(None) when the file simply
/// isn't there yet — first run — so the caller can show the setup UI.
/// Returns Err when the file is present but unparseable (typo, corruption).
pub fn load() -> Result<Option<Config>, String> {
    let path = config_path();
    if !path.exists() { return Ok(None); }
    let raw = std::fs::read_to_string(&path)
        .map_err(|e| format!("read {}: {}", path.display(), e))?;
    let mut cfg: Config = toml::from_str(&raw)
        .map_err(|e| format!("parse {}: {}", path.display(), e))?;
    cfg.server_url = cfg.server_url.trim_end_matches('/').to_string();
    Ok(Some(cfg))
}

/// Write the config to disk. Only writes `server_url =` when it differs
/// from the shipped default, so a normal user's file stays minimal
/// (token + folder only).
pub fn save(cfg: &Config) -> Result<(), String> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("mkdir {}: {}", dir.display(), e))?;
    let server_line = if cfg.server_url == DEFAULT_SERVER_URL {
        String::new()
    } else {
        format!("server_url      = \"{}\"\n", cfg.server_url)
    };
    // Windows paths use backslashes; TOML strings would need those escaped,
    // and forward slashes work equally well on Windows for filesystem APIs.
    // Normalize on write so the file stays readable.
    let folder = cfg.replays_folder.replace('\\', "/");
    let body = format!(
        "# taiko-trainer uploader companion config\n\
         # Generated by the uploader app. Edit as needed.\n\n\
         {}api_token       = \"{}\"\n\
         replays_folder  = \"{}\"\n\
         poll_interval_s = {}\n",
        server_line, cfg.api_token, folder, cfg.poll_interval_s,
    );
    std::fs::write(config_path(), body)
        .map_err(|e| format!("write {}: {}", config_path().display(), e))?;
    Ok(())
}

/// Best-effort probe for the osu! replays folder. Returns None on failure;
/// caller should fall back to asking the user via the folder picker.
pub fn detect_replays_folder() -> Option<PathBuf> {
    let mut candidates: Vec<PathBuf> = Vec::new();
    // Windows: standard per-user install
    if let Ok(local) = std::env::var("LOCALAPPDATA") {
        candidates.push(PathBuf::from(local).join("osu!").join("Data").join("r"));
    }
    // Older / manual Windows installs
    candidates.push(PathBuf::from("C:/osu!/Data/r"));
    candidates.push(PathBuf::from("C:/Program Files/osu!/Data/r"));
    candidates.push(PathBuf::from("C:/Program Files (x86)/osu!/Data/r"));
    // Linux (osu-lazer / stable-under-wine)
    if let Some(home) = dirs::home_dir() {
        candidates.push(home.join(".local/share/osu-wine/osu!/Data/r"));
        candidates.push(home.join("osu!/Data/r"));
        // macOS (rare for taiko but included)
        candidates.push(home.join("Library/Application Support/osu!/Data/r"));
    }
    candidates.into_iter().find(|c| c.is_dir())
}
